/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AetherfieldRouteImport } from './routes/aetherfield'
import { Route as KiboriRouteImport } from './routes/kibori'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentMarksRouteImport } from './routes/student.marks'
import { Route as StudentPerformanceRouteImport } from './routes/student.performance'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherMarksRouteImport } from './routes/teacher.marks'
import { Route as TeacherPerformanceRouteImport } from './routes/teacher.performance'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AetherfieldRoute = AetherfieldRouteImport.update({
  id: '/aetherfield',
  path: '/aetherfield',
  getParentRoute: () => rootRouteImport,
} as any)
const KiboriRoute = KiboriRouteImport.update({
  id: '/kibori',
  path: '/kibori',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMarksRoute = StudentMarksRouteImport.update({
  id: '/student/marks',
  path: '/student/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPerformanceRoute = StudentPerformanceRouteImport.update({
  id: '/student/performance',
  path: '/student/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMarksRoute = TeacherMarksRouteImport.update({
  id: '/teacher/marks',
  path: '/teacher/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPerformanceRoute = TeacherPerformanceRouteImport.update({
  id: '/teacher/performance',
  path: '/teacher/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/teacher/students',
  path: '/teacher/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aetherfield': typeof AetherfieldRoute
  '/kibori': typeof KiboriRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/marks': typeof StudentMarksRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aetherfield': typeof AetherfieldRoute
  '/kibori': typeof KiboriRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/marks': typeof StudentMarksRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aetherfield': typeof AetherfieldRoute
  '/kibori': typeof KiboriRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/marks': typeof StudentMarksRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aetherfield'
    | '/kibori'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/admin/branches'
    | '/admin/departments'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/student/attendance'
    | '/student/marks'
    | '/student/performance'
    | '/student/profile'
    | '/teacher/attendance'
    | '/teacher/marks'
    | '/teacher/performance'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aetherfield'
    | '/kibori'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/admin/branches'
    | '/admin/departments'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/student/attendance'
    | '/student/marks'
    | '/student/performance'
    | '/student/profile'
    | '/teacher/attendance'
    | '/teacher/marks'
    | '/teacher/performance'
    | '/teacher/students'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/aetherfield'
    | '/kibori'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/admin/branches'
    | '/admin/departments'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/student/attendance'
    | '/student/marks'
    | '/student/performance'
    | '/student/profile'
    | '/teacher/attendance'
    | '/teacher/marks'
    | '/teacher/performance'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AetherfieldRoute: typeof AetherfieldRoute
  KiboriRoute: typeof KiboriRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentMarksRoute: typeof StudentMarksRoute
  StudentPerformanceRoute: typeof StudentPerformanceRoute
  StudentProfileRoute: typeof StudentProfileRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherMarksRoute: typeof TeacherMarksRoute
  TeacherPerformanceRoute: typeof TeacherPerformanceRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aetherfield': {
      id: '/aetherfield'
      path: '/aetherfield'
      fullPath: '/aetherfield'
      preLoaderRoute: typeof AetherfieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kibori': {
      id: '/kibori'
      path: '/kibori'
      fullPath: '/kibori'
      preLoaderRoute: typeof KiboriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/marks': {
      id: '/student/marks'
      path: '/student/marks'
      fullPath: '/student/marks'
      preLoaderRoute: typeof StudentMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/performance': {
      id: '/student/performance'
      path: '/student/performance'
      fullPath: '/student/performance'
      preLoaderRoute: typeof StudentPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/marks': {
      id: '/teacher/marks'
      path: '/teacher/marks'
      fullPath: '/teacher/marks'
      preLoaderRoute: typeof TeacherMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/performance': {
      id: '/teacher/performance'
      path: '/teacher/performance'
      fullPath: '/teacher/performance'
      preLoaderRoute: typeof TeacherPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/teacher/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AetherfieldRoute: AetherfieldRoute,
  KiboriRoute: KiboriRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentMarksRoute: StudentMarksRoute,
  StudentPerformanceRoute: StudentPerformanceRoute,
  StudentProfileRoute: StudentProfileRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherMarksRoute: TeacherMarksRoute,
  TeacherPerformanceRoute: TeacherPerformanceRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
